DELIMETER = "-_-"
MAX_NUM_OF_CONTACTS = 100
MAX_NUM_OF_CONTACT_LISTS = 150

DB_IP_KEY = 'ip'
DB_PORT_KEY = 'port'

SUCCESS_CODE = 200
# register
FAILURE_CODE_DUPLICATE_CONTACT = 455
FAILURE_CODE_MAX_NUM_CONTACTS = 456
# create
FAILURE_CODE_DUPLICATE_LIST = 457
FAILURE_CODE_MAX_NUM_LISTS = 458
# join / exit
FAILURE_CODE_UNREGISTERED_CONTACT = 459
FAILURE_CODE_UNCREATED_LIST = 460
FAILURE_CODE_DUPLICATE_CONTACT_IN_LIST = 461
# save
FAILURE_CODE_FILE_SAVE_ERROR = 462
